import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // --- ResearchCrew design-system tokens (literal, from researchcrew_ds/DESIGN.md) ---
        "on-tertiary": "#3c2e1a",
        "on-surface": "#e5e2e3",
        "surface-container-high": "#2a2a2b",
        "surface-variant": "#353436",
        "on-error": "#690005",
        "surface-container-low": "#1b1b1d",
        "on-primary-container": "#7b8193",
        "on-error-container": "#ffdad6",
        secondary: "#c4c7c9",
        "on-secondary": "#2d3133",
        outline: "#909096",
        "on-primary-fixed-variant": "#414756",
        "surface-bright": "#39393a",
        "secondary-fixed": "#e0e3e5",
        "on-secondary-fixed-variant": "#444749",
        "surface-container-lowest": "#0e0e0f",
        "secondary-fixed-dim": "#c4c7c9",
        "tertiary-container": "#221605",
        "error-container": "#93000a",
        "surface-container-highest": "#353436",
        "on-tertiary-container": "#927e65",
        "tertiary-fixed-dim": "#dac3a7",
        "surface-tint": "#c1c6d9",
        "inverse-surface": "#e5e2e3",
        tertiary: "#dac3a7",
        "on-surface-variant": "#c6c6cc",
        "primary-fixed-dim": "#c1c6d9",
        "surface-dim": "#131314",
        "tertiary-fixed": "#f8dfc1",
        "primary-container": "#121826",
        "on-primary": "#2a303f",
        "primary-fixed": "#dde2f6",
        "surface-container": "#201f21",
        "inverse-on-surface": "#313031",
        "on-secondary-container": "#b6b9bb",
        "outline-variant": "#45464c",
        error: "#ffb4ab",
        "on-secondary-fixed": "#191c1e",
        "secondary-container": "#464a4b",
        "on-background": "#e5e2e3",
        "on-primary-fixed": "#151b29",
        "on-tertiary-fixed": "#261907",
        "inverse-primary": "#585e6f",
        "on-tertiary-fixed-variant": "#54442f",
        background: "#131314",
        surface: "#131314",
        primary: "#c1c6d9",

        // --- Legacy alias tokens kept for existing components; repointed at
        // the DS palette above so the whole app reskins without a mass
        // find/replace across every component file. ---
        bg: "#131314",
        surface2: "#2a2a2b",
        border: "#45464c",
        primary2: "#dde2f6",
        accent: "#38bdf8",
        ink: "#e5e2e3",
        inkMuted: "#c6c6cc",
        success: "#10b981",
        warn: "#f59e0b",
        danger: "#ffb4ab",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "1rem",
        "stack-gap": "0.75rem",
        "sidebar-width": "280px",
        "panel-padding": "1.5rem",
        "container-max": "1440px",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "Inter", "sans-serif"],
        mono: ["var(--font-jbmono)", "JetBrains Mono", "monospace"],
        geist: ["Geist", "var(--font-inter)", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-sm": ["Geist", "sans-serif"],
        "code-sm": ["var(--font-jbmono)", "JetBrains Mono", "monospace"],
        "headline-md": ["Geist", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-caps": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-md-mobile": ["Geist", "sans-serif"],
      },
      fontSize: {
        // DS scale
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "code-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md-mobile": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        // legacy aliases kept for existing components
        h1: ["28px", { lineHeight: "1.25", fontWeight: "700" }],
        h2: ["20px", { lineHeight: "1.3", fontWeight: "600" }],
        body: ["14px", { lineHeight: "1.55" }],
        feed: ["13px", { lineHeight: "1.5" }],
      },
      backgroundImage: {
        "hero-gradient": "linear-gradient(135deg, #8b5cf6, #38bdf8)",
      },
      boxShadow: {
        glow: "0 0 24px rgba(139,92,246,.15)",
      },
      keyframes: {
        "pulse-ring": {
          "0%": { boxShadow: "0 0 0 0 rgba(139,92,246,0.5)" },
          "70%": { boxShadow: "0 0 0 8px rgba(139,92,246,0)" },
          "100%": { boxShadow: "0 0 0 0 rgba(139,92,246,0)" },
        },
        "glow-sweep": {
          "0%": { boxShadow: "0 0 0 rgba(56,189,248,0)" },
          "50%": { boxShadow: "0 0 18px rgba(56,189,248,0.65)" },
          "100%": { boxShadow: "0 0 0 rgba(56,189,248,0)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        breathe: {
          "0%, 100%": { opacity: "1", transform: "scale(1)" },
          "50%": { opacity: "0.5", transform: "scale(0.95)" },
        },
        "pulse-dot": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: ".5" },
        },
      },
      animation: {
        "pulse-ring": "pulse-ring 2s infinite",
        "glow-sweep": "glow-sweep 1.4s ease-in-out 2",
        shimmer: "shimmer 2s infinite linear",
        breathe: "breathe 3s ease-in-out infinite",
        "pulse-dot": "pulse-dot 2s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
    },
  },
  plugins: [],
};
export default config;
